import { Inter } from "next/font/google";
import { ApolloWrapper } from "./lib/apollo-wrapper.js";
import Navbar from "./components/Navbar.js";
import Header from "./Header/page.js";
import "./globals.css";
import { Provider } from "./components/Clients.jsx";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
        {/* <Navbar/> */}
        <Provider>
            <Header />
            {children}
            <Toaster/>
        </Provider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
